name: Check Sources
on:
  schedule:
    - cron: "0 0 */2 * *" # every 48 hours
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run script
        run: python proxy_checker.py
        env:
          SOURCE1: ${{ secrets.SOURCE1 }}
