name: Check POE Token
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Run check.sh script
        run: |
          cd poe_token_check
          chmod +x check.sh
          ./check.sh
        env:
          DTOKEN: ${{ secrets.DTOKEN }}
          DCHANNEL: ${{ secrets.DCHANNEL }}

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "New poe token dump & Update date.txt"
          git push
