name: Check proxies
on:
  schedule:
    - cron: "0 0 */4 * *" # every 4 days
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run script
        run: python proxy_check/proxy_checker.py
        env:
          SOURCE1: ${{ secrets.SOURCE1 }}
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add proxy_list.txt
          git commit -m "Update proxy list"
          git -c http.extraheader="AUTHORIZATION: basic ${{ secrets.GTOKEN }}" push
        env:
          GTOKEN: ${{ secrets.GTOKEN }}
