name: Cleaning Data
on:
  workflow_run:
    workflows: ["Check POE Token"]
    types:
      - completed

jobs:
  clean:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run csv_to_txt.py script
        run: |
          cd poe_token_check
          python csv_to_txt.py

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Cleaned chat data"
          git push
